version: 2.1

jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run:
          name: Install Pi-hole
          command: |
            apt-get update
            apt-get install -y wget sudo
            wget -O /etc/pihole/setupVars.conf https://pastebin.com/raw/YBpWALGg
            wget -O basic-install.sh https://install.pi-hole.net
            sudo bash basic-install.sh

workflows:
  version: 2
  your_workflow:
    jobs:
      - build